@echo off
call :log_enter pENV

CALL sENV

SET PROJ_LABEL          =$SYS%
SET PROJ_NET            =$SYS_NET%

SET PROJ_CONT           =%GIS_CONT%
SET PROJ_CONT_DATA_DIR  =%GIS_CONT_DATA_DIR%
SET PROJ_CONT_DIR       =%GIS_CONT_DIR%
SET PROJ_CONT_HOME_DIR  =%GIS_CONT_HOME_DIR%
SET PROJ_HOST           =%GIS_HOST%
SET PROJ_HOST_DIR       =%GIS_HOST_DIR%
SET PROJ_IMG            =%GIS_IMG%
SET PROJ_PASSWORD       =%GIS_PASSWORD%
SET PROJ_PORT_EXT       =%GIS_PORT_EXT%
SET PROJ_PORT_INT       =%GIS_PORT_INT%
SET PROJ_USER           =%GIS_USER%%
SET PROJ_VOL            =%GIS_VOL%
SET PROJ_VOL_DIR        =%GIS_VOL_DIR%

SET PROJ_DB_NAME        =%GIS_DB_NAME%

call :log_exit pENV

