@echo off


CALL LOG_ENTER pENV

call sENV
call pENV_MOD

SET "PROJ_LABEL=%SYS_NAME%"
SET "PROJ_NET=%SYS_NET%"

SET "PROJ_CONT=%GIS_CONT%"
SET "PROJ_CONT_DATA_DIR=%GIS_CONT_DATA_DIR%"
SET "PROJ_CONT_DIR=%GIS_CONT_DIR%"
SET "PROJ_CONT_HOME_DIR=%GIS_CONT_HOME_DIR%"
SET "PROJ_HOST_DIR=%GIS_HOST_DIR%"
SET "PROJ_IMG=%GIS_IMG%"
SET "PROJ_PORT_INT=%GIS_PORT_INT%"
SET "PROJ_VOL=%GIS_VOL%"
SET "PROJ_VOL_DIR=%GIS_VOL_DIR%"


CALL LOG_EXIT pENV

